#!/usr/bin/env bash

# Navigation
alias .='pwd'
alias ..='cd ..'

# List options
alias l='ls'
alias lf='ls -lqF'				# list with file type recognition chars
alias la='ls -lqFa'				# list all files
alias lk='ls -lSr'    			# list sorted by size
alias ll='ls -lag $* | more'	# view file(s)
alias ls='ls -aF --color'

# Prevent accidental clobbering of files
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Admin
alias cdwd='cd `pwd`'
alias chx='chmod +x'
alias cwd='echo $cwd'
alias df='df -kh'
alias du='du -h'
alias h='history'
alias ifconfig='/sbin/ifconfig'
#alias killall='sudo killall'
alias path='echo -e ${PATH//:/\\n}'
alias rl='rlogin'
# alias server_name='ssh -v -l USERNAME IP ADDRESS'
alias which='type -all'

# System
alias reboot='sudo /sbin/shutdown -r now'
alias shutdown='sudo /sbin/shutdown -h now'
alias suspend='sudo pm-suspend'
#alias sleep='sudo pm-suspend'

# Applications and utilities
alias apache2ctl='sudo /usr/sbin/apache2ctl'
alias eclipse-php='/usr/local/bin/eclipse-php/eclipse'
alias eclipse='/usr/local/bin/eclipse/eclipse'
#alias gvim='gvim -p --remote-tab-silent'
alias gvim='UBUNTU_MENUPROXY= gvim'
alias escputil='sudo escputil'
alias inklevel='escputil -iqur /dev/usb/lp0'
alias randline="/usr/bin/rl"
alias tidy='tidy -config $HOME/.tidy.conf'
alias updatedb='sudo updatedb'
alias vi='vim'
alias open='xdg-open'
alias shred='shred -fvzu'
